version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - .env
    restart: always
    networks:
      - database_network
    volumes:
      - ./mysql:/var/lib/mysql

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    env_file:
      - .env
    restart: always 
    depends_on:
      - mysql
    command: sh -c './wait-for mysql:3306 && 
              python manage.py migrate --settings=surveyapp.settings.production && 
              gunicorn -c config/gunicorn/conf.py --bind 0.0.0.0:8000 --chdir surveyapp surveyapp.wsgi:application'
    volumes:
      - .:/surveyapp
    networks:
      - database_network
      - nginx_network
  
  # reverse proxy container (nginx)
  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/surveyapp/static
      - ./media:/surveyapp/media
      - ./acme:/var/www/acme-challenge
    networks:
      - nginx_network
    depends_on:
      - django

networks:
  database_network:
    driver: bridge
  nginx_network:
    driver: bridge
