version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
    - .env
    restart: always
    networks:
      - database_network
    volumes:
      - ./mysql:/var/lib/mysql

  django:
    build: .
    container_name: django
    env_file:
    - .env
    restart: always 
    depends_on:
      - mysql
   # command: sh -c './wait-for mysql:3306'
    volumes:
      - .:/surveyapp
    networks:
      - database_network
      - nginx_network
  
  # reverse proxy container (nginx)
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/surveyapp/static
      - ./media:/surveyapp/media
    networks:
      - nginx_network
    depends_on:
      - django

networks:
  database_network:
    driver: bridge
  nginx_network:
    driver: bridge