version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
    - .env
    restart: always 
    networks:
      - back
    volumes:
      - ./mysql:/var/lib/mysql

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django
    restart: always 
    networks:
      - back
    volumes:
      - .:/surveyapp
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    depends_on:
      - mysql
    ports:
      - 8082:80
    networks:
      - back

networks:
  back: