# Generated by Django 2.2 on 2019-05-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresponse',
            options={'verbose_name': 'User Response', 'verbose_name_plural': 'User  Responses'},
        ),
    ]
