# Generated by Django 2.2 on 2019-05-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190527_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
    ]
