# Generated by Django 2.2 on 2019-05-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190531_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
